import "server-only";

import { DEALERS_FILE, PRODUCTS_FILE, SALES_FILE } from "@/lib/config";
import { readJsonFile } from "@/lib/storage/json-file";
import type { Dealer, Product, SalesLine } from "@/lib/types";

/**
 * Reads the three mock datasets. They are generated by
 * scripts/generate-mock-data.ts and nothing at runtime writes them, except
 * Feature 2 approvals which will edit the price list.
 *
 * A missing file is an empty list rather than an error: the app should still
 * render and say it has no data.
 */

export async function readProducts(): Promise<Product[]> {
  return (await readJsonFile<Product[]>(PRODUCTS_FILE)) ?? [];
}

export async function readDealers(): Promise<Dealer[]> {
  return (await readJsonFile<Dealer[]>(DEALERS_FILE)) ?? [];
}

export async function readSales(): Promise<SalesLine[]> {
  return (await readJsonFile<SalesLine[]>(SALES_FILE)) ?? [];
}

/** The catalogue we currently stock. Discontinued products stay in the file. */
export function activeProducts(products: Product[]): Product[] {
  return products.filter((product) => !product.status);
}
